#!/usr/bin/env bash
# Run full provenance and secret audit for the repository.
# Intended to be executed locally before any public release.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
TIMESTAMP=$(date -u +"%Y%m%dT%H%M%SZ")

# Output directory (outside repo, private)
AUDIT_OUT="${REPO_ROOT}/../contrib/sus-oss/private-audits/sus-analytics-web"
mkdir -p "${AUDIT_OUT}"

# 1. Provenance audit (grep)
PROV_FILE="${AUDIT_OUT}/provenance-audit-${TIMESTAMP}.txt"

echo "Running provenance grep..."
git -C "${REPO_ROOT}" grep -i -n -E "manus|base44|codex|chatgpt|openai|claude|anthropic|copilot|gemini|llm|large language model|ai-generated|ai generated|generated by|co-authored-by|assistant|inteligência artificial|inteligencia artificial" -- . > "${PROV_FILE}" || true

echo "Provenance audit saved to ${PROV_FILE}"

# 2. Secret scan using gitleaks (if installed)
if command -v gitleaks >/dev/null 2>&1; then
  echo "Running gitleaks secret scan..."
  GITLEAKS_FILE="${AUDIT_OUT}/gitleaks-report-${TIMESTAMP}.json"
  gitleaks detect --source "${REPO_ROOT}" --report-path "${GITLEAKS_FILE}" --redact
  echo "Gitleaks report saved to ${GITLEAKS_FILE}"
else
  echo "gitleaks not installed; skipping secret scan."
fi

echo "Audit completed."
